# frozen_string_literal: true

require "fileutils"

module Meringue
  # Writes the small `meringue` launcher that makes the command work from
  # anywhere, pointed at one checkout.
  #
  # Installing from a clone used to leave the command available only through
  # `bundle exec ruby -Ilib bin/meringue`. This is what both install paths use
  # to finish the job — the installer calls it after cloning, and the Gemfile
  # calls it during `bundle install` so a clone ends up in the same place.
  #
  # Deliberately standalone: it is loaded by the Gemfile, before the rest of
  # Meringue (or any dependency) is available, so it must require nothing but
  # stdlib.
  module Shim
    NAME = "meringue"
    OPT_OUT = "MERINGUE_NO_SHIM"
    BIN_DIR_ENV = "MERINGUE_BIN_DIR"
    DEFAULT_BIN_DIR = "~/.local/bin"

    INSTALLED = "installed"
    UNCHANGED = "unchanged"
    SKIPPED = "skipped"
    FAILED = "failed"

    module_function

    def default_bin_dir(env: ENV)
      configured = env[BIN_DIR_ENV].to_s
      File.expand_path(configured.empty? ? DEFAULT_BIN_DIR : configured)
    end

    def opted_out?(env: ENV)
      !env[OPT_OUT].to_s.strip.empty?
    end

    # `exec` rather than a wrapper process, and an explicit --gemfile so the
    # command works from any directory rather than only from the checkout.
    def contents(source_dir)
      root = File.expand_path(source_dir)
      <<~SHIM
        #!/bin/sh
        # Generated by Meringue. Runs the checkout in #{root}.
        # Delete this file, or set #{OPT_OUT}=1, to stop it being rewritten.
        exec #{command(root)} "$@"
      SHIM
    end

    def path(bin_dir: nil, env: ENV)
      File.join(bin_dir || default_bin_dir(env: env), NAME)
    end

    # Never raises and never fails the thing that called it: a read-only bin
    # directory is a reason to print how to fix it, not to fail `bundle install`.
    def install!(source_dir:, bin_dir: nil, env: ENV)
      return result(SKIPPED, message: "") if opted_out?(env: env)

      directory = bin_dir || default_bin_dir(env: env)
      target = File.join(directory, NAME)
      body = contents(source_dir)
      return result(UNCHANGED, path: target, message: on_path_message(directory, target, env: env)) if current?(target, body)

      FileUtils.mkdir_p(directory)
      File.write(target, body)
      FileUtils.chmod(0o755, target)
      result(INSTALLED, path: target, message: "Installed #{target}\n#{on_path_message(directory, target, env: env)}")
    rescue SystemCallError, IOError => e
      result(
        FAILED,
        path: target,
        message: "Could not write #{target} (#{e.message}). Meringue still runs with: #{command(source_dir)}"
      )
    end

    def command(source_dir)
      root = File.expand_path(source_dir)
      %(bundle exec --gemfile="#{root}/Gemfile" ruby "#{root}/bin/#{NAME}")
    end

    def current?(target, body)
      File.file?(target) && File.executable?(target) && File.read(target) == body
    rescue SystemCallError, IOError
      false
    end

    # A shim nobody can reach is worse than no shim, because it looks done.
    def on_path?(directory, env: ENV)
      env["PATH"].to_s.split(File::PATH_SEPARATOR).any? do |entry|
        !entry.empty? && File.expand_path(entry) == File.expand_path(directory)
      end
    end

    def on_path_message(directory, target, env: ENV)
      return "Run `#{NAME}` from anywhere." if on_path?(directory, env: env)

      "#{directory} is not on your PATH. Add this to your shell startup file:\n" \
        "  export PATH=\"#{directory}:$PATH\"\n" \
        "Until then, run #{target} directly."
    end

    # Bundler evaluates the Gemfile more than once per `bundle install`, so
    # without this the same paragraph prints twice. The module is only required
    # once, so its state is what survives between those evaluations.
    def announced!
      return true if @announced

      @announced = true
      false
    end

    def result(status, path: nil, message: "")
      { "status" => status, "path" => path, "message" => message }.compact
    end
  end
end
